spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${OAUTH_GIT_HUB_APP_CLIENT_ID}
            clientSecret: ${OAUTH_GIT_HUB_APP_CLIENT_SECRET}
        ## Spring Boot が裏側で設定している値
        # provider:
        #   github:
        #     authorization-uri: https://github.com/login/oauth/authorize
        #     token-uri: https://github.com/login/oauth/access_token
        #     user-info-uri: https://api.github.com/user
        #     user-name-attribute: id
